on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      
      - name: Install packages
        run: |
          sudo npm i -g mermaid-filter
          #node /usr/local/lib/node_modules/mermaid-filter/node_modules/puppeteer/install.js
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends chromium lmodern pandoc texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended texlive-pictures
      
      - name: Convert all md from wiki folder to pdf
        run: |
          export CHROME_BIN=$(which chromium)
          find wiki -name "*.md" -exec pandoc -F mermaid-filter -f markdown -t latex -o {}.pdf {} \;
          mv wiki/*.pdf docs
          # Remove ".md" from pdf filenames
          for i in docs/*.pdf; do mv "$i" "`echo $i | sed 's/\.md//'`" | true; done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            docs/*.pdf
          labels: documentation
          title: Update PDFs
          body: |
            This PR updates the PDFs in the docs folder.
          token: ${{ secrets.PAT }}
